name: build-envs-reuseable-workflow
env:
  AWS_REGION: us-east-2
on:
  workflow_call:
    inputs:
      BRANCH:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      SERVICE_NAME:
        required: true
        type: string

      BUILD_SECRETS:
        required: true
        type: string

      BUILD_ENVS:
        required: true
        type: string

      SSM_PARAMS:
        required: true
        type: string
      SSM_SECRETS:
        required: true
        type: string

    outputs:
      ENV_VALUES:
        description: "The first output string"
        value: ${{ jobs.build-envs.outputs.PLAIN_ARRAY }}
      SECRET_YAMLS:
        description: "Array of Base64 Encoded YAML files for secrets"
        value: ${{ jobs.build-envs.outputs.YAMLS_ARRAY }}


jobs:
  build-envs:
    runs-on: ubuntu-latest
    outputs:
      PLAIN_ARRAY: ${{ steps.compose-envs.outputs.PLAIN_ARRAY }}
      YAMLS_ARRAY: ${{ steps.compose-secrets.outputs.YAMLS_ARRAY }}
        

    steps:

      - name: Checkout
        uses: actions/checkout@v2


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_EXPERIMENTAL }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_EXPERIMENTAL }}
          aws-region: us-east-2

      - name: aws-ssm-to-env
        uses: Bundle-App/aws-ssm-to-env@master
        if: ${{ inputs.BUILD_ENVS == 'yes' }}
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_EXPERIMENTAL }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_EXPERIMENTAL }}
        with:
          ssm_parameter_list: ${{inputs.SSM_PARAMS}}
          prefix: PLAIN_



      - name: aws-secrets-to-env
        uses: Bundle-App/aws-ssm-to-env@master
        if: ${{ inputs.BUILD_SECRETS == 'yes' }}
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_EXPERIMENTAL }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_EXPERIMENTAL }}
        with:
          ssm_parameter_list: ${{inputs.SSM_SECRETS}}
          prefix: SECRET_

      - name: Plain Env Variables
        if: ${{ inputs.BUILD_ENVS == 'yes' }}
        id: compose-envs
        run: |

            plains=""
            for var in "${!PLAIN_@}";
            do
              VALUE=${!var}
              k=${var:6}
              
              KEY=$(echo "$k" | tr -d '[:space:]')
            

              echo -n "$VALUE" > "$KEY"

          
            
              plains="${plains}{\"name\":\"${KEY}\",\"value\":\"${VALUE}\"},"  ## Build JSON array of plain keys and values
          
            done

            plains=${plains::-1} ##remove last comma
            plains="{"params":[${plains}]}"
              
            echo "$plains"
            echo ::set-output name=PLAIN_ARRAY::$plains

      - name: Set Array to JSON
        id: set-env
        if: ${{ inputs.BUILD_ENVS == 'yes' }}
        env:
          PLAIN_ARRAY: ${{ steps.compose-envs.outputs.PLAIN_ARRAY }}
        run: |
            ##
            echo "${PLAIN_ARRAY}" > plain.json
      
      - name: Build yaml file
        if: ${{ inputs.BUILD_ENVS == 'yes' }}
        id: build-yaml
        uses: fabasoad/yaml-json-xml-converter-action@main
        with:
          path: 'plain.json'
          from: 'json'
          to: 'yaml'

      - name: Set YAML
        id: set-yaml
        if: ${{ inputs.BUILD_ENVS == 'yes' }}
        run: |
            ##
            rm -f plain.json
            echo "${{steps.build-yaml.outputs.data}}" > params.yaml

      - name: Install Kubeseal & Kubectl
   
        if: ${{ inputs.BUILD_SECRETS == 'yes' }}
        run: |
            #Install kubeseal
            brew update
            brew install kubeseal
            brew install kubectl
      
      - name: Compose Secrets 
        if: ${{ inputs.BUILD_SECRETS == 'yes' }}
        id: compose-secrets 
        env:
          KUBESEAL_CERT: ${{ secrets.KUBESEAL_CERT }}
        run: |
            #Get secrets from env 

            compgen -A variable | grep SECRET > list.txt

            echo -n  $KUBESEAL_CERT | base64 -d > cert.pem
            secrets=""
            YAMLS=""
            
            git_hash=$(git rev-parse --short "$GITHUB_SHA")
            for var in "${!SECRET_@}";
            do
              VALUE=${!var}
              k=${var:7}

            
              touch "$k"
              KEY=$(echo "$k" | tr -d '[:space:]')
              #KEY="${KEY}-${git_hash}"

              echo -n "$VALUE" > "$KEY"

              #SECRET_YAML=$(kubectl create secret generic $KEY -n experimental --from-file="$KEY" --dry-run=client -o yaml | kubeseal --cert cert.pem -o yaml | base64 )

          
              kubectl create secret generic $KEY -n experimental --from-file="$KEY" --dry-run=client -o yaml | kubeseal --cert cert.pem -o yaml > charts/deploy/templates/secrets/"$KEY".yaml
              rm -f "$KEY"
            
              secrets="${secrets}\"${KEY}\","  ## Build JSON array of secret keys
             
          
            done

            #Cleanup files

            rm -f list.txt
            rm -f cert.pem
            secrets=${secrets::-1} ##remove last comma
         
            secrets="[${secrets}]"
         
            
        
            echo ::set-output name=SECRET_ARRAY::$secrets

      - name: Set Secrets to ENV
        if: ${{ inputs.BUILD_SECRETS == 'yes' }}
        id: set-secrets
        env:
          SECRET_ARRAY: ${{ steps.compose-secrets.outputs.SECRET_ARRAY }}

        run: |
            #set secrets in values file

            echo "Setting $SECRET_ARRAY"

            secrets=$(cat ./charts/deploy/values.yaml | grep secretKeys: | awk '{print $2}')
            echo "Old secret $secrets"
            sed -i "s/secretKeys: \[[^]]*\]/secretKeys: ${SECRET_ARRAY}/g" ./charts/deploy/values.yaml

      
      
      
      - name: write
        uses: Bundle-App/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GLOBAL_GITHUB_TOKEN }}
          BRANCH_NAME: ${{inputs.BRANCH}} #optional defaults to master


        
   


