name: reuseable-workflow
env:
  AWS_REGION: us-east-2
on:
  workflow_call:
    inputs:
      BUILD_IMAGE:
        required: false
        type: string
      BUILD_ARGS:
        required: false
        type: string

      ENV_PARAMS:
        required: true
        type: string
      ENV_SECRETS:
        required: true
        type: string

    outputs:
      ECR_IMAGE:
          description: "Ecr Image"
          value: ${{ jobs.build_image.outputs.image }}
  



jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_EXPERIMENTAL }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_EXPERIMENTAL }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        if: ${{ inputs.BUILD_IMAGE== 'yes' }}
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        if: ${{ inputs.BUILD_IMAGE== 'yes' }}
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY_PREFIX: "bundle"
          ECR_REPOSITORY: example-service/staging #Replace this with your service name eg. blockchain-service
          GITHUB_TOKEN: ${{secrets.GLOBAL_GITHUB_TOKEN}}
          ENV_SECRETS: ${{inputs.ENV_SECRETS}}
    

        run: |
          # Build a docker container and push it to ECR

          echo "Hello ${ENV_SECRETS}"
          
          # git_hash=$(git rev-parse --short "$GITHUB_SHA")
          # docker build --build-arg GITHUB_TOKEN --build-arg GITHUB_PACKAGE_REPO  -t $ECR_REGISTRY/$ECR_REPOSITORY_PREFIX/$ECR_REPOSITORY:${GITHUB_REF##*/}-$git_hash .
          # echo "Pushing image to ECR..."
          # docker push $ECR_REGISTRY/$ECR_REPOSITORY_PREFIX/$ECR_REPOSITORY:${GITHUB_REF##*/}-$git_hash
          # echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY_PREFIX/$ECR_REPOSITORY:${GITHUB_REF##*/}-$git_hash"

